name: Cleanup

on:
  schedule:
    - cron: '0 0 * * 0'  # Cada domingo a medianoche

jobs:
  cleanup-images:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Cleanup old ECR images
        run: |
          aws ecr delete-images \
            --repository-name ${{ secrets.ECR_REPOSITORY }} \
            --image-ids $(aws ecr list-images \
              --repository-name ${{ secrets.ECR_REPOSITORY }} \
              --filter tagStatus=UNTAGGED \
              --query 'imageIds[*]' \
              --output json)